// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export { }

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    // ImageBox: typeof import('./.vitepress/component/image-box/index.vue')['default']
    NavUl: typeof import('./.vitepress/component/nav-ul/index.vue')['default']
  }
}
